version: '0.2'
language: en
ignorePaths:
  - node_modules/**
  - .vscode/**
  - .git/**
  - .gitignore
  - migrations/**
words:
  - chanthariroza
  - Cyberhorse
  - Kimlay
  - libsql
  - Nethphorn
  - nosniff
  - paoloargento
  - Phann
  - Pich
  - Rachna
  - skibidii
  - Stylesheet
  - Tepbrathna
  - TURSO
